### ISSUE TITLE
Root Password?

### ISSUE THREAD

**Issue by aregbee** [anmaped/openfang#10]
what is the root password in case I want to switch to another build to try like DafangHacks? I cannot issue the commands to flash the bootloader from the Admin account so making the password available would be quite helpful!

**Comment by jmtatsch** [comment]
Sudo should be included now or just use su.

**Comment by aregbee** [comment]
Thanks, that worked! I was able to set the root password after issuing an su.

Just to clarify...now that I have root access and can issue the appropriate commands, am I able to update from RC4 to RC5 without a PC?

**Comment by jmtatsch** [comment]
Yes

**Comment by anmaped** [comment]
May I close this issue ?
