### ISSUE TITLE
Blinking orange led

### ISSUE THREAD

**Issue by llimz** [anmaped/openfang#11]
@anmaped After some investigations, I can fix my blinking orange led problem by updating the script S40dafang

I changed it from
	# set solid yellow led
	echo none >/sys/class/leds/led_yellow/trigger
	echo 1 >/sys/class/leds/led_yellow/brightness

to:
	# set solid yellow led
	echo none >/sys/class/leds/led_yellow1/trigger
	echo 1 >/sys/class/leds/led_yellow1/brightness

And I've got a simple orange led at the end of the loading process.

**Comment by anmaped** [comment]
Fixed 9dc6c8602101789fe9b554d4d8a4f1f62a14f00b.
