### ISSUE TITLE
is dafang bootloader cross compatible with openfang?

### ISSUE THREAD

**Issue by arkhub** [anmaped/openfang#18]
as the tittle suggest, I have already flashed my dafang 128mb camera with dafang-hack custom u-boot bootloader, and I want to try openfang but without flashing the bootloader again, is it possible?

**Comment by anmaped** [comment]
@arkhub Yes, but not with all of them.

**Comment by anmaped** [comment]
May I close the issue ?

**Comment by arkhub** [comment]
sorry, sure
