### ISSUE TITLE
[T20L Xiaomi Mijia 2018] Certificate and start S50lighttpd must be done manually every time

### ISSUE THREAD

**Issue by jannodeluxe** [anmaped/openfang#28]
To get the webinterface running I have to create the Certificate and start S50lighttpd every time manually (after each reboot)

![image](https://user-images.githubusercontent.com/46295868/55670574-7e56f200-5886-11e9-85eb-bf2587c41ca2.png)

[openfang rc05_01-31-g0fcd6ae]

**Comment by anmaped** [comment]
Already solved in 2d1c9fb.

**Comment by jannodeluxe** [comment]
> Already solved in [2d1c9fb](https://github.com/anmaped/openfang/commit/2d1c9fb46d584aca62d6decbda1102b09443d6ae).

Hi @anmaped is there already a compiled Version with root.ext2 for that? Or do I have to compile myself?
