### ISSUE TITLE
[T20L Xiaomi Mijia 2018] Buttons inverted in Webinterface

### ISSUE THREAD

**Issue by jannodeluxe** [anmaped/openfang#30]
It seems that some or even alle Buttons are inverted in Webinterface. Proof:

When clicking the ON Button for LED (Blue and Yellow) the LED is OFF
When clicking the OFF Button for LED (Blue and Yellow) the LED is ON

![image](https://user-images.githubusercontent.com/46295868/55670612-f9b8a380-5886-11e9-91f2-5eac0bad7be1.png)

**Comment by anmaped** [comment]
Fixed b869345a5f43f249c6bcf50cc2dc8e8665215ac1.
