### ISSUE TITLE
default nvram settings of SXJ02ZM

### ISSUE THREAD

**Issue by mgx0** [anmaped/openfang#35]
Hi,

does anybody have a possibility to export nvram settings (not the certificate, that can be recreated)?

I flushed nvram and lost the pin assignments. Since then also wifi stopped working (connects and gets IP address, but does not communicate)

using this command `nvram show`

thanks

**Comment by anmaped** [comment]
`nvram clear rtdev; nvram commit` and do a reboot! This will factory reset the device!

**Comment by mgx0** [comment]
EDIT: thanks a lot, that did it. I needed to reset rtdev layout, then configure the camera and all nvram entries have reappeared. thanks
