### ISSUE TITLE
fix wyze cam 2 tinted image

### ISSUE THREAD

**Issue by raulvasquez** [anmaped/openfang#36]
I had issues with my wzye cams having a green tinted image. I found this issue on dafang-hacks and it fixed my issue with the image in openfang:

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/813

Pretty easy fix.

**Comment by anmaped** [comment]
Fixed e410ae4e0d09243c5f6bcd724d692006d2492256.
