### ISSUE TITLE
autoupdate

### ISSUE THREAD

**Issue by cnopix** [anmaped/openfang#37]
Hi,

i have an issue when i load the autoupdate.

![20190612_055137876_iOS](https://user-images.githubusercontent.com/29841868/59343552-6aa78c00-8d0c-11e9-8751-455464a50362.jpg)

i check the date and it's correct.

can you help me ?

**Comment by anmaped** [comment]
Hi @cnopix 

The autoupdate will only works over openfang releases. You are using a compiled firmware without the tag release. I guess is that the problem.

**Comment by cnopix** [comment]
Hi @anmaped 

So, i need to reflash the firmware on the chip ?

**Comment by lenisko** [comment]
@cnopix No. You don't have to touch chip, just re-flash `rootfs`.
