### ISSUE TITLE
Difference to EliasKotlyar/Xiaomi-Dafang-Hacks

### ISSUE THREAD

**Issue by klainkaliber** [anmaped/openfang#43]
Hi,
what is the difference between _openfang_ and _Xiaomi-Dafang-Hacks_?
Is one building upon the other?

**Comment by jmtatsch** [comment]
Openfang is inspired by Xiaomi-Dafang-Hacks and basically a cleaner, leaner, saner version of it :)

**Comment by anmaped** [comment]
I guess @jmtatsch explained it.
