### ISSUE TITLE
Update docker instructions

### ISSUE THREAD

**Issue by fischermario** [anmaped/openfang#44]
The docker instructions are outdated. Instead of

```
docker pull anmaped/openfang
docker run --name openfangdev anmaped/openfang
docker exec -d openfangdev sh /root/openfang/buildopenfang.sh
```

you should run

```
docker run -it -d --name openfangdev anmaped/openfang
docker exec openfangdev sh /root/openfang/buildopenfang.sh
```

The "docker pull" command is unnecessary and the "docker run" command is incomplete as it creates a container that is not able to start and run continuously. I have removed the detach option from the "docker exec" command because otherwise the user does not see the process finishing. Btw the same applies to the section "Build openfang from git repository".

The path in the "docker cp" command is also invalid. Change it to:

```
docker cp openfangdev:/root/openfang/_build/buildroot-2016.02/output/images/. .
```

Please update the instructions to reflect those changes. This will save a lot of users some hours of head scratching. Thank you!

**Comment by anmaped** [comment]
@fischermario Thanks for the info. I'll update it or if you want you could help us by just submitting a pull request.
