### ISSUE TITLE
Build script fails when run on host without selinux support

### ISSUE THREAD

**Issue by tssva** [anmaped/openfang#5]
The build script uses the `cp --preserve=context` command which fails when the hosts kernel is built without selinux support. In my case on Ubuntu 18.04.

I have a patch which currently addresses this by checking for kernel selinux support and only including the `--preserve=context` option in that case. My question is whether the option is really needed? I have built many open source projects and this is the first time I have seen it used in the build script for one. I don't have a system with selinux to test with. If it is, I will submit a pull request with the patch. Otherwise I will submit one with the option fully removed.

**Comment by anmaped** [comment]
Yes, It's true. I think we can remove it.
