### ISSUE TITLE
Does not work with every DIGOO DG W30

### ISSUE THREAD

**Issue by ChrisLuck** [anmaped/openfang#55]
I bought a DIGOO DG W30, took it apart and noticed two things:
- it is using a "GOKE 7102" SoC (this means it will not work with openfang)
- one of the two antennas is fake

So i do not recommend to buy this camera unless you are very sure that you get a version with the ingenic t20 SoC.

**Comment by anmaped** [comment]
@ChrisLuck Could you post some pictures?
