### ISSUE TITLE
Build fails on hosts with openssl 1.1.0

### ISSUE THREAD

**Issue by tssva** [anmaped/openfang#6]
If openssl 1.1.0 is installed on the build host compiling the Python _ssl and _hashlib modules fails causing the buildroot compile to fail.

The python build appears to be using the openssl headers installed on the build host instead of those of the buildroot openssl package. If the build host has openssl 1.1.0 installed this causes the build to fail because python 2.7 is not compatible with openssl 1.1.0.

**Comment by anmaped** [comment]
I'm using `OpenSSL 1.1.0h-fips  27 Mar 2018`. Could you explain your setup ?

**Comment by anmaped** [comment]
Is the problems building host-python-2.7.11 package ? The openssl is compiled by builldroot two times `host-openssl-1.0.2g` and `openssl-1.0.2g`. One is for the buildroot host and the other for the buildroot target. How can buildroot be using a different host then that ?

**Comment by tssva** [comment]
My mistake. I didn't realize that it was building once for the host and then for the target platform. I assumed the error was happening when building for the target, but checking it is failing for host-python.

**Comment by tssva** [comment]
host-openssl is not being built which is why host-python is using the openssl 1.1.0 headers in the host's /usr/include. Now to figure out why host-openssl isn't being built.

**Comment by tssva** [comment]
Did some research and found the issue. host-python is built with ssl disabled; however, if the python build process detects the openssl header files during build it will try to build _ssl anyways in order to use the openssl hash routines for _hashlib. This fails when openssl 1.1.0 is installed. 

There are patches available which disable the check for openssl and has python use it's built-in version of the hash routines instead of openssl ones. I will submit a PR with the patches.

**Comment by anmaped** [comment]
But do you know why in your system buildroot is not building host-openssl?

**Comment by tssva** [comment]
host-python is built first because host-openssl isn't a dependency for it.
